spring:
  datasource:
    url: jdbc:mysql://localhost:3306/department?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: liubenwei01
mybatis:
  type-aliases-package: com.qiu.department.entity
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml
jwt:
  header: Authorization   #jwt的请求头
  secret: eyJleHAiOjE1NDMyMDUyODUsInN1YiI6ImFkbWluIiwiY3Jl   #jwt的加密字符串
  expiration: 18000000  #jwt token有效时间（毫秒）（半个小时）
  refreshToken: 6000000      #jwt 距离刷新时间(间隔10分钟)